name: CI

on:
  push:
  pull_request:
  schedule:
  # monthly
  - cron: '0 0 1 * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-24.04
          - macos-13
          - macos-14 # (arm64)
          - macos-14-xlarge # (arm64)
          - macos-14-large
          - macos-15 # (arm64)
          - macos-15-xlarge #or macos-15 (arm64)
          - macos-15-intel
          - macos-15-large
          - macos-26-xlarge # (arm64)
          - macos-latest #(depends [arm])
          - macos-latest-large #(depends)

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v4

    - name: Install
      run: |
        source conda-ci install $OPT

    - name: Test
      run: |
        source activate base
        echo CONDA_PREFIX is "$CONDA_PREFIX"
        conda list
        source conda-ci install-conda-build
        conda list
        conda build -c conda-forge recipe
        #tree  "$CONDA_PREFIX"/conda-bld
        #tree  "$CONDA_PREFIX"
        ls "$CONDA_PREFIX"/conda-bld/*/testme*conda
